### PR TITLE
Code Cleanup for `relecov_dashboard`

### PR DESCRIPTION
**Pull request by Daniel-VM**
## PR Description

This PR addresses several tasks for cleaning up the code in the `relecov_dashboard` .
Changes:
-  Imports Cleanup:
    - Consolidated related imports.
    - Replaced direct imports of functions and variables with consolidated imports.
    - Ordered the imports.
 
- Refactoring of files allocation:
    - Moved files to more appropriate directories to reduce the number of files in the `utils` directory.
    - Updated import statements accordingly.

### Notes
I have added "# FIXME" tags across files to check them in the future.

### Future work
Additional cleanup tasks and potential refactoring may be required based on the outcomes of the initial cleanup.

### CODE REVIEW

**Comment by saramonzon** [comment]
I like it! But i'd remove the second level of folders inside utils

**Comment by saramonzon** [comment]
LGTM, but once @Shettland PR is merged, you'll need to adjust the import naming accordingly to its rename, p.e "bioinfo_analysis_handling" to bioinfo_analysis

**Comment by saramonzon** [comment]
or did you talk about this and decided to do it in another PR?

**Comment by Shettland** [comment]
> LGTM, but once @Shettland PR is merged, you'll need to adjust the import naming accordingly to its rename, p.e "bioinfo_analysis_handling" to bioinfo_analysis

My PR already addresses that, I'll solve the conflicts once this one is merged

**Comment by saramonzon** [comment]
> > LGTM, but once @Shettland PR is merged, you'll need to adjust the import naming accordingly to its rename, p.e "bioinfo_analysis_handling" to bioinfo_analysis
> 
> My PR already addresses that, I'll solve the conflicts once this one is merged

I don't mean conflicts, but errors that will arise in the website as the imports would not be found with the changed paths

**Review by Shettland — APPROVED** [review]
LGTM

**Comment by Shettland** [comment]
> > > LGTM, but once @Shettland PR is merged, you'll need to adjust the import naming accordingly to its rename, p.e "bioinfo_analysis_handling" to bioinfo_analysis
> > 
> > 
> > My PR already addresses that, I'll solve the conflicts once this one is merged
> 
> I don't mean conflicts, but errors that will arise in the website as the imports would not be found with the changed paths

Yes I know, I have changed the imports that are affected in relecov_dashborad from renaming files in relecov_core in my PR, then I'll resolve conflicts and update the imports affected in relecov_core from this PR

**Comment by saramonzon** [comment]
ok perfe! Pues rebasead

**Pull request merged**
